"""create debt ledger tables

Revision ID: 99ef2d53f976
Revises: 9f3c1a2b4d5e
Create Date: 2026-07-01 00:09:00.302848
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ef2d53f976'
down_revision: Union[str, None] = '9f3c1a2b4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_user_id'), 'counterparties', ['user_id'], unique=False)
    op.create_index('uq_counterparties_user_name', 'counterparties', ['user_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('debts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('counterparty_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.Enum('I_OWE', 'OWED_TO_ME', name='debt_direction'), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('incurred_on', sa.Date(), nullable=False),
    sa.Column('written_off_at', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('principal_amount > 0', name='ck_debts_principal_positive'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_counterparty_id'), 'debts', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_debts_user_id'), 'debts', ['user_id'], unique=False)
    op.create_table('repayments',
    sa.Column('debt_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_repayments_amount_positive'),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayments_debt_id'), 'repayments', ['debt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_repayments_debt_id'), table_name='repayments')
    op.drop_table('repayments')
    op.drop_index(op.f('ix_debts_user_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_counterparty_id'), table_name='debts')
    op.drop_table('debts')
    # create_table auto-creates the PG enum type; drop_table does not remove it, so do it here
    # explicitly (otherwise a re-upgrade fails with "type debt_direction already exists").
    op.execute('DROP TYPE debt_direction')
    op.drop_index('uq_counterparties_user_name', table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_user_id'), table_name='counterparties')
    op.drop_table('counterparties')
