"""create transactions ledger tables

Revision ID: d17b6fd71465
Revises: 99ef2d53f976
Create Date: 2026-07-03 21:20:24.600935
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17b6fd71465'
down_revision: Union[str, None] = '99ef2d53f976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_index('uq_categories_user_name', 'categories', ['user_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('transactions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='transaction_direction'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(direction = 'OUT' AND category_id IS NOT NULL) OR (direction = 'IN' AND category_id IS NULL)", name='ck_transactions_category_direction'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Data backfill (decision 2026-07-03): every account starts with the default category set.
    # New signups get it from the registration service; this backfills users created before
    # this migration. The list mirrors DEFAULT_CATEGORIES in app/modules/transactions/service.py
    # (duplicated on purpose — migrations must not import app code that keeps evolving).
    op.execute(
        """
        INSERT INTO categories (user_id, name, icon)
        SELECT u.id, d.name, d.icon
        FROM users u
        CROSS JOIN (VALUES
            ('Rent', 'home'),
            ('Groceries', 'cart'),
            ('Utilities', 'bolt'),
            ('Phone & net', 'wifi'),
            ('Transport & gas', 'car'),
            ('Family support', 'heart'),
            ('Eating out', 'fork'),
            ('Coffee', 'cup'),
            ('Cigarettes', 'smoke'),
            ('Gym', 'dumbbell'),
            ('Dating', 'spark'),
            ('Clothes', 'shirt'),
            ('Subscriptions', 'play'),
            ('Savings', 'piggy')
        ) AS d(name, icon)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_table('transactions')
    # create_table auto-creates the PG enum type; drop_table does not remove it, so do it here
    # explicitly (otherwise a re-upgrade fails with "type transaction_direction already exists").
    op.execute('DROP TYPE transaction_direction')
    op.drop_index('uq_categories_user_name', table_name='categories')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
